export { MenuContentPage } from "./menu-content.page"
export {ProducsList} from "./products-list.page"
export {ShoppingCart} from "./shoping-cart.page"
export {LoginPage} from "./login.page"
export {AddressStepPage} from "./address-step.page"
export {ShippingStepPage} from "./shipping-step.page"
export {PaymentStepPage} from "./payment-step.page"
export {DressesListPage} from "./dresses-list.page"
export {PersonalFormPage} from "./personal-form.page"
export {personalInfo, persona1} from "../models/personalInformation.page"
export {FormAssertions} from "../e2e/questions/form-assertions.page"
